### PR TITLE
v0.1.5

### PR DESCRIPTION
**Pull request by v0lta**
**What's new**:
 - added additional test cases for our `wavedec3` and 1D-matrix transformation code.
  - 3d matrix transformation support.  The new matrix-wavedecs3 returns a list of dictionaries like https://pywavelets.readthedocs.io/en/latest/ref/nd-dwt-and-idwt.html#multilevel-decomposition-wavedecn .
  - The `separable_conv_transform` module now provides support for separable padded transforms.
 - improved handling of the internal "channel"-dimension for the padded 2d-fwt case. Output tensors from `wavedec2` now have the shape [batch, height, width] instead of [batch, 1, height, width]. 
 - Added shape checks for the transformed coefficients, for more informative error messages.
 - Added tests for just in time compilation. See `test/test_jit.py` for more details.

**Breaking changes**:
  - since https://arxiv.org/pdf/2210.14874.pdf found them to work well,  the faster separable transforms are now the default for all boundary wavelet computations. If you require `wavedec2` and `MatrixWavedec2` to produce identical coefficients in the `Haar` case, set `separable` to `False`.
  - to simplify the documentation `_get_pad` is now private.
  - To ensure our API is compatible with `pywt` the padded analysis transforms argument order has changed. The order is now always `data, wavelet, mode, level`.

### CODE REVIEW

**Comment by v0lta** [comment]
https://github.com/v0lta/PyTorch-Wavelet-Toolbox/pull/50 has the separable cont transforms for v.0.1.5

**Review by v0lta — COMMENTED** [review]
Looks great, thanks @felixblanke .

**Review by felixblanke — COMMENTED** [review]
Looks good to me. Thank you @v0lta

Do we want to add a public function for the `n`-dimensional fully separable (convolutional) fwt? Currently, it is only public for n=1,2,3.
The only problem I can see is that we could not distinguish between n-dim data and batched (n-1)-dim data, as it is currently done for the "fixed n" implementations.

**Comment by v0lta** [comment]
Thanks, Felix. Not having a publicly available function might be better since we do not support n-dimensional inputs anywhere else. The toolbox feels more consistent this way.

**Comment by felixblanke** [comment]
It bugged me that the `separable` attribute of `WaveletPacket2D` was ignored for convolutional transforms, so I added support for it. However I am not really happy with the necessary conversions between the `[Tensor, Tuple[Tensor, ...]]` and `[Tensor, Dict[str, Tensor]]` formats.

Btw: I have no clue why one test failed for [cc74842](https://github.com/v0lta/PyTorch-Wavelet-Toolbox/pull/46/commits/cc74842061a19dc95e29cd33141c063aef410176)

**Comment by felixblanke** [comment]
Currently, the default for `WaveletPacket2D` are non-separable transforms. Should we switch that to separable as well or keep it at non-separable?

**Comment by v0lta** [comment]
It should remain non-separable to ensure results are consistent with the pywt-packets.

**Comment by v0lta** [comment]
Ah, I see you added support for separable conv transforms for the 2D packets. Thank you! In this case, I would leave the defaults unchanged because I expect most users to want pywt-compatible results.

**Comment by v0lta** [comment]
The jit tests run just fine with torch 2.0 . I have tested this. https://github.com/v0lta/PyTorch-Wavelet-Toolbox/issues/51 is now closed. We should merge. Other changes should go into future releases.

**Pull request merged**
